---
deploy_root: /opt/docker-epicbook
repo_local_path: /home/paul/Projects/AWS/week14/epicbook docker/theepicbook
compose_project_src: "{{ deploy_root }}/app"
compose_file: compose.yaml
app_env_local_source: "{{ repo_local_path }}/.env.remote"
app_env_example: "{{ compose_project_src }}/.env.example"
app_env_file: "{{ compose_project_src }}/.env"
docker_packages:
  - docker.io
  - docker-compose-v2
  - rsync
  - curl
docker_service_name: docker
