---
app_root: /opt/theepicbook
app_user: ubuntu
node_major_version: "18"
epicbook_repo_url: "https://github.com/lua-cloud03/theepicbook.git"
epicbook_repo_version: "main"
epicbook_database: bookstore
epicbook_db_host: "epicbook-assignment-mysql.cg7sgummo8d3.us-east-1.rds.amazonaws.com"
epicbook_db_username: epicbookadmin
epicbook_db_password: "ChangeMe123!"
epicbook_port: 8080
server_name: "_"
backend_private_ip: "10.42.11.197"
frontend_public_ip: "54.88.173.63"
epicbook_verify_url: "http://127.0.0.1:8080/"
nginx_verify_url: "http://127.0.0.1/"
